apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "mychart.name" . }}
spec:
  rules:
    - host: asptesting.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mychart.fullname" . }}
                port:
                  number: 80