apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "mychart.name" . }}
spec:
  selector:
    app: {{ include "mychart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

